/**
 * KAST Central Data Store
 * Fully localized in English with Euro (€ / EUR) as the primary base currency.
 * Zero weekend transactions (strictly business days: Monday through Friday).
 */

export const profileData = {
  name: "SAMUEL",
  handle: "@user_csrxi8992",
  fullName: "Samuel",
  lastName: "Fasawe",
  dob: "Jun 11, 1997",
  email: "cuentakastt38@gmail.com",
  phone: "+54 11 7829-1323",
  membership: "STANDARD",
  tier: "Tier 1 Member",
  version: "3.25.2 (737)",
  address: "33 The Meadows, Ballymena, County Antrim BT43 7NG, UK",
  country: "United Kingdom",
  kycStatus: "Verified",
  kastTag: "samuel.kast"
};

export const bankData = {
  // EUR SEPA Account (Primary Main Account)
  eurAccountName: "Samuel Fasawe",
  eurIban: "FR7630006000011234567890189",
  eurBic: "BNPAFRPPXXX",
  eurBankName: "Kast Europe / BNP Paribas Partner",
  eurBankAddress: "16 Boulevard des Italiens, 75009 Paris",
  eurCountry: "France",
  eurAccountType: "SEPA Instant Checking",

  // USD Checking Account (Lead Bank)
  accountName: "Samuel Fasawe",
  accountNumber: "216677917073",
  routingNumber: "101019644",
  wireRouting: "101019644",
  address: "42 Carlos Tejedor, Lomas de Zamora, Buenos Aires B1834",
  bankName: "Lead Bank in the USA",
  bankAddress: "1801 Main St., Kansas City, MO 64108",
  country: "USA",
  swiftCode: "LEADUS33XXX",
  accountType: "Checking",

  // UK ClearBank Account
  ukAccountName: "Samuel Fasawe",
  ukAccountNumber: "04288613",
  ukSortCode: "04-28-86",
  ukIban: "GB84CLRB04288613032354",
  ukBankName: "ClearBank Limited",
  ukBankAddress: "Level 27, The Broadgate Tower, 20 Primrose Street, London, EC2A 2EW",
  ukCountry: "United Kingdom",
  ukSwift: "CLRBGB22XXX"
};

export const dashboardData = {
  balance: "€0.94",
  totalBalanceRaw: 0.94,
  currency: "EUR",
  cardsCount: 1,
  activePerks: 3,
  carouselSlides: [
    { id: "total", title: "TOTAL BALANCE", amount: "€0.94", subtitle: "All accounts & wallets", change: "+4.2% this week" },
    { id: "eur", title: "EUR SEPA ACCOUNT", amount: "€0.94", subtitle: "Kast Europe SEPA ···0189", change: "Available now" },
    { id: "usd", title: "USD CHECKING", amount: "$0.00", subtitle: "Lead Bank ···7073", change: "Zero balance" },
    { id: "crypto", title: "CRYPTO PORTFOLIO", amount: "€0.00", subtitle: "USDC, USDT, ETH, BTC", change: "0 active tokens" },
    { id: "rewards", title: "KAST REWARDS", amount: "1,420 PTS", subtitle: "Value: €14.20", change: "5% cashback active" }
  ]
};

export const cardData = {
  holder: "SAMUEL FASAWE",
  type: "Visa Infinite Black",
  network: "VISA",
  currency: "EUR",
  maskedNumber: "4532 •••• •••• 8824",
  fullNumber: "4532 8920 1842 8824",
  expiry: "08/29",
  cvv: "842",
  isFrozen: false,
  dailyLimit: 5000,
  spentToday: 454.48,
  monthlyLimit: 25000,
  spentMonth: 6124.90,
  onlinePayments: true,
  contactless: true,
  international: true,
  atmWithdrawals: true
};

/**
 * Historical and recent transaction ledger.
 * All amounts are in EUR as requested.
 * Strictly scheduled on business weekdays (Monday-Friday), zero weekend entries.
 */
export const transactions = [
  // --- OCTOBER 2026 ---
  {
    id: "tx_oct_01",
    title: "Card Purchase",
    toFrom: "Apple Store Champs-Élysées",
    amount: "- 1,199.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "02 Oct · 04:30 PM",
    month: "OCTOBER 2026",
    category: "Card Purchase",
    reference: "POS-99812",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_oct_02",
    title: "Cashback Reward",
    toFrom: "KAST 5% Elite Cashback",
    amount: "+ 59.95 EUR",
    type: "in",
    status: "completed",
    dateTime: "02 Oct · 04:31 PM",
    month: "OCTOBER 2026",
    category: "Reward",
    reference: "REW-99813",
    fee: "€0.00",
    account: "Rewards Wallet"
  },
  {
    id: "tx_oct_03",
    title: "SEPA Instant Transfer",
    toFrom: "From BNP Paribas Wealth",
    amount: "+ 3,500.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "02 Oct · 11:15 AM",
    month: "OCTOBER 2026",
    category: "SEPA Transfer",
    reference: "SEPA-20261002-01",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_oct_04",
    title: "Card Purchase",
    toFrom: "Uber BV Amsterdam",
    amount: "- 38.40 EUR",
    type: "out",
    status: "completed",
    dateTime: "01 Oct · 08:20 PM",
    month: "OCTOBER 2026",
    category: "Card Purchase",
    reference: "POS-99742",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_oct_05",
    title: "Online Subscription",
    toFrom: "OpenAI ChatGPT Plus",
    amount: "- 22.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "01 Oct · 09:00 AM",
    month: "OCTOBER 2026",
    category: "Subscription",
    reference: "SUB-88192",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },

  // --- SEPTEMBER 2026 ---
  {
    id: "tx_sep_01",
    title: "Bank Transfer",
    toFrom: "From Stripe Payments Europe",
    amount: "+ 4,280.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "30 Sep · 03:10 PM",
    month: "SEPTEMBER 2026",
    category: "Merchant Payout",
    reference: "SEPA-20260930-08",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_sep_02",
    title: "Card Purchase",
    toFrom: "LVMH Moët Hennessy Paris",
    amount: "- 640.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "29 Sep · 02:45 PM",
    month: "SEPTEMBER 2026",
    category: "Card Purchase",
    reference: "POS-98104",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_sep_03",
    title: "Cashback Reward",
    toFrom: "KAST 5% Elite Cashback",
    amount: "+ 32.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "29 Sep · 02:46 PM",
    month: "SEPTEMBER 2026",
    category: "Reward",
    reference: "REW-98105",
    fee: "€0.00",
    account: "Rewards Wallet"
  },
  {
    id: "tx_sep_04",
    title: "Sent",
    toFrom: "To As4Q...J78f",
    amount: "- 850.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "28 Sep · 11:30 AM",
    month: "SEPTEMBER 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x8821b...4490",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  {
    id: "tx_sep_05",
    title: "Bank Transfer",
    toFrom: "From TORB...HLIN",
    amount: "+ 1,500.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "25 Sep · 09:20 AM",
    month: "SEPTEMBER 2026",
    category: "Wire Transfer",
    reference: "KAST-20260925-01",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_sep_06",
    title: "Card Purchase",
    toFrom: "Air France VIP Lounge",
    amount: "- 185.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "24 Sep · 07:15 AM",
    month: "SEPTEMBER 2026",
    category: "Card Purchase",
    reference: "POS-97210",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_sep_07",
    title: "Sent",
    toFrom: "To Elena_VIP",
    amount: "- 250.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "22 Sep · 06:40 PM",
    month: "SEPTEMBER 2026",
    category: "Internal Transfer",
    reference: "KAST-20260922-04",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_sep_08",
    title: "Bank Transfer",
    toFrom: "From ClearBank GBP Exchange",
    amount: "+ 2,150.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "21 Sep · 01:25 PM",
    month: "SEPTEMBER 2026",
    category: "FX Transfer",
    reference: "FX-20260921-02",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_sep_09",
    title: "Card Purchase",
    toFrom: "Amazon EU SARL",
    amount: "- 124.90 EUR",
    type: "out",
    status: "completed",
    dateTime: "18 Sep · 05:10 PM",
    month: "SEPTEMBER 2026",
    category: "Card Purchase",
    reference: "POS-96302",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_sep_10",
    title: "Sent",
    toFrom: "To As4Q...J78f",
    amount: "- 400.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "17 Sep · 10:15 AM",
    month: "SEPTEMBER 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x7712a...1984",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  {
    id: "tx_sep_11",
    title: "Bank Transfer",
    toFrom: "From Google Cloud EMEA",
    amount: "+ 1,850.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "15 Sep · 02:40 PM",
    month: "SEPTEMBER 2026",
    category: "Direct Deposit",
    reference: "SEPA-20260915-05",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_sep_12",
    title: "Card Purchase",
    toFrom: "Monoprix Haussmann Paris",
    amount: "- 56.80 EUR",
    type: "out",
    status: "completed",
    dateTime: "14 Sep · 12:30 PM",
    month: "SEPTEMBER 2026",
    category: "Card Purchase",
    reference: "POS-95101",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_sep_13",
    title: "ATM Cash Withdrawal",
    toFrom: "BNP Paribas ATM Paris",
    amount: "- 200.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "11 Sep · 03:00 PM",
    month: "SEPTEMBER 2026",
    category: "ATM Withdrawal",
    reference: "ATM-20260911-01",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_sep_14",
    title: "Bank Transfer",
    toFrom: "From TORB...HLIN",
    amount: "+ 3,100.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "09 Sep · 11:05 AM",
    month: "SEPTEMBER 2026",
    category: "Wire Transfer",
    reference: "KAST-20260909-02",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_sep_15",
    title: "Card Purchase",
    toFrom: "SNCF TGV First Class",
    amount: "- 168.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "07 Sep · 08:45 AM",
    month: "SEPTEMBER 2026",
    category: "Card Purchase",
    reference: "POS-94210",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_sep_16",
    title: "Online Subscription",
    toFrom: "Spotify Technology SA",
    amount: "- 14.99 EUR",
    type: "out",
    status: "completed",
    dateTime: "04 Sep · 07:00 AM",
    month: "SEPTEMBER 2026",
    category: "Subscription",
    reference: "SUB-83910",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_sep_17",
    title: "Bank Transfer",
    toFrom: "From Revolut Ltd Europe",
    amount: "+ 950.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "03 Sep · 04:15 PM",
    month: "SEPTEMBER 2026",
    category: "SEPA Transfer",
    reference: "SEPA-20260903-01",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_sep_18",
    title: "Sent",
    toFrom: "To As4Q...J78f",
    amount: "- 500.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "01 Sep · 10:00 AM",
    month: "SEPTEMBER 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x6618c...9011",
    fee: "€0.00",
    account: "Solana Wallet"
  },

  // --- AUGUST 2026 ---
  {
    id: "tx_aug_01",
    title: "Bank Transfer",
    toFrom: "From Stripe Payments Europe",
    amount: "+ 3,750.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "31 Aug · 02:30 PM",
    month: "AUGUST 2026",
    category: "Merchant Payout",
    reference: "SEPA-20260831-09",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_aug_02",
    title: "Card Purchase",
    toFrom: "Four Seasons Hotel George V",
    amount: "- 820.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "28 Aug · 09:15 PM",
    month: "AUGUST 2026",
    category: "Card Purchase",
    reference: "POS-93108",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_aug_03",
    title: "Cashback Reward",
    toFrom: "KAST 5% Elite Cashback",
    amount: "+ 41.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "28 Aug · 09:16 PM",
    month: "AUGUST 2026",
    category: "Reward",
    reference: "REW-93109",
    fee: "€0.00",
    account: "Rewards Wallet"
  },
  {
    id: "tx_aug_04",
    title: "Sent",
    toFrom: "To As4Q...J78f",
    amount: "- 620.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "27 Aug · 11:20 AM",
    month: "AUGUST 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x5519d...2108",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  {
    id: "tx_aug_05",
    title: "Bank Transfer",
    toFrom: "From TORB...HLIN",
    amount: "+ 2,200.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "25 Aug · 10:45 AM",
    month: "AUGUST 2026",
    category: "Wire Transfer",
    reference: "KAST-20260825-03",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_aug_06",
    title: "Card Purchase",
    toFrom: "Decathlon Paris Rive Gauche",
    amount: "- 112.50 EUR",
    type: "out",
    status: "completed",
    dateTime: "24 Aug · 04:10 PM",
    month: "AUGUST 2026",
    category: "Card Purchase",
    reference: "POS-92104",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_aug_07",
    title: "Sent",
    toFrom: "To Marcus_FX",
    amount: "- 300.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "21 Aug · 03:20 PM",
    month: "AUGUST 2026",
    category: "Internal Transfer",
    reference: "KAST-20260821-01",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_aug_08",
    title: "Bank Transfer",
    toFrom: "From BNP Paribas Treasury",
    amount: "+ 1,400.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "19 Aug · 01:10 PM",
    month: "AUGUST 2026",
    category: "SEPA Transfer",
    reference: "SEPA-20260819-02",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_aug_09",
    title: "Card Purchase",
    toFrom: "Deliveroo France",
    amount: "- 34.50 EUR",
    type: "out",
    status: "completed",
    dateTime: "17 Aug · 07:50 PM",
    month: "AUGUST 2026",
    category: "Card Purchase",
    reference: "POS-91204",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_aug_10",
    title: "ATM Cash Withdrawal",
    toFrom: "Credit Agricole ATM Paris",
    amount: "- 250.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "14 Aug · 11:00 AM",
    month: "AUGUST 2026",
    category: "ATM Withdrawal",
    reference: "ATM-20260814-01",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_aug_11",
    title: "Bank Transfer",
    toFrom: "From TORB...HLIN",
    amount: "+ 1,800.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "12 Aug · 09:30 AM",
    month: "AUGUST 2026",
    category: "Wire Transfer",
    reference: "KAST-20260812-05",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_aug_12",
    title: "Sent",
    toFrom: "To As4Q...J78f",
    amount: "- 750.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "10 Aug · 04:15 PM",
    month: "AUGUST 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x4419a...1102",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  {
    id: "tx_aug_13",
    title: "Card Purchase",
    toFrom: "Galeries Lafayette Paris",
    amount: "- 280.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "07 Aug · 03:40 PM",
    month: "AUGUST 2026",
    category: "Card Purchase",
    reference: "POS-90214",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_aug_14",
    title: "Bank Transfer",
    toFrom: "From ClearBank GBP Clearing",
    amount: "+ 2,500.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "05 Aug · 10:15 AM",
    month: "AUGUST 2026",
    category: "FX Transfer",
    reference: "FX-20260805-01",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_aug_15",
    title: "Online Subscription",
    toFrom: "Amazon Prime Video",
    amount: "- 6.99 EUR",
    type: "out",
    status: "completed",
    dateTime: "03 Aug · 08:00 AM",
    month: "AUGUST 2026",
    category: "Subscription",
    reference: "SUB-79104",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },

  // --- JULY 2026 ---
  {
    id: "tx_jul_01",
    title: "Bank Transfer",
    toFrom: "From Stripe Payments Europe",
    amount: "+ 3,100.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "31 Jul · 03:00 PM",
    month: "JULY 2026",
    category: "Merchant Payout",
    reference: "SEPA-20260731-01",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_jul_02",
    title: "Card Purchase",
    toFrom: "Eurostar International London",
    amount: "- 225.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "30 Jul · 10:30 AM",
    month: "JULY 2026",
    category: "Card Purchase",
    reference: "POS-89102",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_jul_03",
    title: "Sent",
    toFrom: "To As4Q...J78f",
    amount: "- 450.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "28 Jul · 02:15 PM",
    month: "JULY 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x3312c...8819",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  {
    id: "tx_jul_04",
    title: "Bank Transfer",
    toFrom: "From TORB...HLIN",
    amount: "+ 1,950.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "24 Jul · 11:00 AM",
    month: "JULY 2026",
    category: "Wire Transfer",
    reference: "KAST-20260724-04",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_jul_05",
    title: "Card Purchase",
    toFrom: "Nespresso Boutique Paris",
    amount: "- 78.40 EUR",
    type: "out",
    status: "completed",
    dateTime: "22 Jul · 04:20 PM",
    month: "JULY 2026",
    category: "Card Purchase",
    reference: "POS-88192",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_jul_06",
    title: "Sent",
    toFrom: "To Elena_VIP",
    amount: "- 150.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "20 Jul · 01:45 PM",
    month: "JULY 2026",
    category: "Internal Transfer",
    reference: "KAST-20260720-02",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_jul_07",
    title: "Bank Transfer",
    toFrom: "From Google Cloud EMEA",
    amount: "+ 1,600.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "17 Jul · 09:15 AM",
    month: "JULY 2026",
    category: "Direct Deposit",
    reference: "SEPA-20260717-06",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_jul_08",
    title: "Card Purchase",
    toFrom: "Uber Eats Paris",
    amount: "- 42.10 EUR",
    type: "out",
    status: "completed",
    dateTime: "15 Jul · 08:30 PM",
    month: "JULY 2026",
    category: "Card Purchase",
    reference: "POS-87190",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_jul_09",
    title: "Sent",
    toFrom: "To As4Q...J78f",
    amount: "- 380.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "13 Jul · 11:10 AM",
    month: "JULY 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x2219b...7710",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  {
    id: "tx_jul_10",
    title: "Bank Transfer",
    toFrom: "From TORB...HLIN",
    amount: "+ 2,800.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "10 Jul · 10:20 AM",
    month: "JULY 2026",
    category: "Wire Transfer",
    reference: "KAST-20260710-01",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_jul_11",
    title: "Card Purchase",
    toFrom: "Apple Services Subscription",
    amount: "- 16.99 EUR",
    type: "out",
    status: "completed",
    dateTime: "08 Jul · 07:00 AM",
    month: "JULY 2026",
    category: "Subscription",
    reference: "SUB-76192",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_jul_12",
    title: "ATM Cash Withdrawal",
    toFrom: "Societe Generale ATM Paris",
    amount: "- 300.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "06 Jul · 02:40 PM",
    month: "JULY 2026",
    category: "ATM Withdrawal",
    reference: "ATM-20260706-01",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  {
    id: "tx_jul_13",
    title: "Bank Transfer",
    toFrom: "From BNP Paribas Clearing",
    amount: "+ 1,250.00 EUR",
    type: "in",
    status: "completed",
    dateTime: "03 Jul · 11:45 AM",
    month: "JULY 2026",
    category: "SEPA Transfer",
    reference: "SEPA-20260703-05",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  {
    id: "tx_jul_14",
    title: "Sent",
    toFrom: "To As4Q...J78f",
    amount: "- 520.00 EUR",
    type: "out",
    status: "completed",
    dateTime: "01 Jul · 09:30 AM",
    month: "JULY 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x1192a...6601",
    fee: "€0.00",
    account: "Solana Wallet"
  },

  // --- JUNE 2026 (Existing transactions adjusted strictly to EUR & weekdays) ---
  { 
    id: "0", 
    title: "Bank Transfer", 
    toFrom: "From TORB...HLIN", 
    amount: "+ 54.48 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "23 Jun · 10:17 AM", 
    month: "JUNE 2026",
    category: "SEPA Transfer",
    reference: "KAST-20260623-01",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  { 
    id: "1", 
    title: "Bank Transfer", 
    toFrom: "To TORB...HLIN", 
    amount: "- 54.48 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "23 Jun · 10:17 AM", 
    month: "JUNE 2026",
    category: "Internal Transfer",
    reference: "KAST-20260623-02",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  { 
    id: "2", 
    title: "Bank Transfer", 
    toFrom: "From KeCh... LLC", 
    amount: "+ 4,500.00 EUR", 
    type: "in", 
    status: "processing", 
    dateTime: "22 Jun · 02:04 PM", 
    month: "JUNE 2026",
    category: "Wire Transfer",
    reference: "KAST-20260622-03",
    fee: "€0.00",
    account: "SEPA EUR Account",
    note: "Under compliance review - documentation requested"
  },
  { 
    id: "3", 
    title: "Sent", 
    toFrom: "To As4Q...J78f", 
    amount: "- 1,144.14 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "22 Jun · 10:48 AM", 
    month: "JUNE 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x78f2a...89b1",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  { 
    id: "4", 
    title: "Bank Transfer", 
    toFrom: "From TORB...HLIN", 
    amount: "+ 1,140.88 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "22 Jun · 10:27 AM", 
    month: "JUNE 2026",
    category: "Wire Transfer",
    reference: "KAST-20260622-04",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  { 
    id: "5", 
    title: "Sent", 
    toFrom: "To As4Q...J78f", 
    amount: "- 202.20 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "19 Jun · 08:14 PM", 
    month: "JUNE 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x9182a...7710",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  { 
    id: "6", 
    title: "Bank Transfer", 
    toFrom: "From Kim ...chke", 
    amount: "+ 205.59 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "19 Jun · 08:07 PM", 
    month: "JUNE 2026",
    category: "SEPA Transfer",
    reference: "KAST-20260619-06",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  { 
    id: "7", 
    title: "Sent", 
    toFrom: "To As4Q...J78f", 
    amount: "- 21.52 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "19 Jun · 01:35 PM", 
    month: "JUNE 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x5192b...3182",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  { 
    id: "8", 
    title: "Sent", 
    toFrom: "To As4Q...J78f", 
    amount: "- 4,425.42 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "19 Jun · 10:34 AM", 
    month: "JUNE 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x6189c...1092",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  { 
    id: "9", 
    title: "Bank Transfer", 
    toFrom: "From TORB...HLIN", 
    amount: "+ 4,446.82 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "19 Jun · 10:17 AM", 
    month: "JUNE 2026",
    category: "Wire Transfer",
    reference: "KAST-20260619-09",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  { 
    id: "10", 
    title: "Sent", 
    toFrom: "To As4Q...J78f", 
    amount: "- 425.42 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "16 Jun · 04:13 PM", 
    month: "JUNE 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x7719a...4401",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  { 
    id: "11", 
    title: "Bank Transfer", 
    toFrom: "From RODI...OTEA", 
    amount: "+ 427.47 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "16 Jun · 02:26 PM", 
    month: "JUNE 2026",
    category: "Wire Transfer",
    reference: "KAST-20260616-11",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  { 
    id: "12", 
    title: "Sent", 
    toFrom: "To As4Q...J78f", 
    amount: "- 231.23 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "16 Jun · 10:32 AM", 
    month: "JUNE 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x3310a...9921",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  { 
    id: "13", 
    title: "Bank Transfer", 
    toFrom: "From OSVA...NDEZ", 
    amount: "+ 230.99 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "16 Jun · 10:19 AM", 
    month: "JUNE 2026",
    category: "Wire Transfer",
    reference: "KAST-20260616-13",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  { 
    id: "14", 
    title: "Sent", 
    toFrom: "To As4Q...J78f", 
    amount: "- 340.34 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "12 Jun · 08:27 AM", 
    month: "JUNE 2026",
    category: "Crypto Transfer (USDC)",
    reference: "0x9921d...4102",
    fee: "€0.00",
    account: "Solana Wallet"
  },
  { 
    id: "15", 
    title: "Bank Transfer", 
    toFrom: "From Curr...loud", 
    amount: "+ 342.93 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "12 Jun · 10:24 AM", 
    month: "JUNE 2026",
    category: "SEPA Transfer",
    reference: "KAST-20260612-15",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },

  // --- MAY 2026 ---
  { 
    id: "16", 
    title: "Card Purchase", 
    toFrom: "Apple Store London", 
    amount: "- 199.00 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "28 May · 03:15 PM", 
    month: "MAY 2026",
    category: "Card Purchase",
    reference: "POS-89104",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },
  { 
    id: "17", 
    title: "Cashback Reward", 
    toFrom: "KAST 5% Elite Cashback", 
    amount: "+ 9.95 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "28 May · 03:16 PM", 
    month: "MAY 2026",
    category: "Reward",
    reference: "REW-89105",
    fee: "€0.00",
    account: "Rewards Wallet"
  },
  { 
    id: "18", 
    title: "Bank Transfer", 
    toFrom: "From Stripe Payments Europe", 
    amount: "+ 2,850.00 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "15 May · 11:20 AM", 
    month: "MAY 2026",
    category: "Merchant Payout",
    reference: "KAST-20260515-18",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  { 
    id: "19", 
    title: "Card Purchase", 
    toFrom: "Uber Rides Paris", 
    amount: "- 28.50 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "08 May · 09:45 PM", 
    month: "MAY 2026",
    category: "Card Purchase",
    reference: "POS-78192",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  },

  // --- APRIL 2026 ---
  { 
    id: "20", 
    title: "Bank Transfer", 
    toFrom: "From Google Cloud EMEA", 
    amount: "+ 1,500.00 EUR", 
    type: "in", 
    status: "completed", 
    dateTime: "22 Apr · 02:10 PM", 
    month: "APRIL 2026",
    category: "Direct Deposit",
    reference: "KAST-20260422-20",
    fee: "€0.00",
    account: "SEPA EUR Account"
  },
  { 
    id: "21", 
    title: "Subscription", 
    toFrom: "OpenAI ChatGPT Plus", 
    amount: "- 20.00 EUR", 
    type: "out", 
    status: "completed", 
    dateTime: "17 Apr · 08:00 AM", 
    month: "APRIL 2026",
    category: "Online Subscription",
    reference: "SUB-19402",
    fee: "€0.00",
    account: "KAST Black Metal Card"
  }
];

export const notificationsData = [
  {
    id: "account_cancellation",
    type: "in",
    title: "Account Compliance Advisory",
    date: "4 min ago",
    message: "Hello Samuel,\n\nWe hope this message finds you well. We sincerely appreciate you choosing KAST for your digital banking needs.\n\nFollowing a recent compliance review, we regret to inform you that we must proceed with reviewing your virtual EUR account operations. Any deposited funds will be fully refunded to originating verified accounts if verification is not finalized.\n\nThank you for your cooperation.\n\nSincerely,\nKAST Compliance Team",
    unread: true,
    section: "TODAY"
  },
  {
    id: "verification_submitted",
    type: "in",
    title: "Verification in Review",
    date: "10 min ago",
    message: "We have successfully received your compliance documentation and explanations for your EUR transfers. Our regulatory compliance specialists are currently reviewing your file. You will receive an automated notification as soon as your funds are approved and released.",
    unread: true,
    section: "TODAY"
  },
  {
    id: "1",
    type: "in",
    title: "You Received €€€",
    date: "02 Oct · 11:15 AM",
    message: "You received a SEPA Instant deposit of 3,500.00 EUR into your French SEPA Account from BNP Paribas Wealth.",
    unread: true,
    section: "TODAY"
  },
  {
    id: "2",
    type: "out",
    title: "Your €€€ is on its way!",
    date: "02 Oct · 04:30 PM",
    message: "Your card payment of 1,199.00 EUR at Apple Store Champs-Élysées has been cleared with zero FX fees.",
    unread: false,
    section: "TODAY"
  },
  {
    id: "3",
    type: "in",
    title: "Funds Held: Action Required",
    date: "22 Jun · 02:04 PM",
    message: "Your pending deposit of 4,500.00 EUR is currently undergoing compliance review.\nTo meet standard financial security regulations and expedite release of your funds, please provide the following details:\n- Your business or personal relationship with the sender.\n- Detailed explanation of the 'Operating Expenses' purpose declared on the wire.\n- Relevant supporting documentation, invoices, or service agreements.\nYou have 7 business days to submit the required documentation. Thank you for your cooperation.",
    unread: false,
    section: "TODAY"
  },
  {
    id: "4",
    type: "out",
    title: "Your €€€ is on its way!",
    date: "22 Jun · 10:48 AM",
    message: "We dispatched 1,144.14 EUR in USDC to the designated recipient wallet address.",
    unread: false,
    section: "TODAY"
  },
  {
    id: "5",
    type: "in",
    title: "You Received €€€",
    date: "22 Jun · 10:27 AM",
    message: "You received a Wire deposit of 1,140.88 EUR into your account from TORB...HLIN.",
    unread: false,
    section: "TODAY"
  }
];

export const securitySettings = {
  biometricsEnabled: true,
  twoFactorEnabled: true,
  loginAlerts: true,
  freezeCardOnSuspicious: true,
  activeSessions: [
    { device: "iPhone 15 Pro (Current)", location: "Paris, France", ip: "194.28.112.4", active: true },
    { device: "MacBook Pro 16", location: "London, UK", ip: "82.165.197.10", active: false }
  ]
};

export const limitsData = {
  currency: "EUR",
  dailyLimit: 10000,
  dailySpent: 4500,
  monthlyAtm: 5000,
  monthlyAtmUsed: 650,
  monthlyWire: 50000,
  monthlyWireUsed: 12400,
  cryptoTransfer24h: 25000,
  cryptoTransfer24hUsed: 2750
};
